apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: wvqpm2fb3-python
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-python:fd287c21cab394e153c26bccc29e688c8567d1d1@sha256:cb70da384c45c0e4d6a32c56aba479ba91720bb42d8e9b776a51d5706326ba5c
          name: container-image
